### ISSUE TITLE
Training data for hate speech and sentiment analysis in Spanish

### ISSUE THREAD

**Issue by isabellevaldes** [pysentimiento/pysentimiento#31]
Hello,

I'm having trouble finding thorough documentation for how to use further training data for conducting hate-speech and sentiment analysis in Spanish. Can you direct me towards the specific documentation that outlines this? Also, how do we distinguish between the different models (BETO, robertuito, etc)? Thanks.

**Comment by finiteautomata** [comment]
Hi @isabellevaldes. I think that looking through the code of this library may not help you a lot, so I'd rather refer to `huggingface` tutorial. Check this:

[Text classification with transformers](https://huggingface.co/docs/transformers/tasks/sequence_classification)

Following this, you will be able to train your own algorithm using as a base BETO, RoBERTuito, or whatever base model you like. Also, you could use your own dataset instead of the one selected in there.

Let me know if you have any problems with this

**Comment by finiteautomata** [comment]
Closing this, feel free to contact me on email if you have any questions
